### ISSUE TITLE
maven.cagataygurturk.com responds with 403 Forbidden

### ISSUE THREAD

**Issue by sandeepraju** [cagataygurturk/aws-lambda-local-runner#1]
I have been trying to use this, but I am unable to get the artifact

[ERROR] Failed to execute goal on project aws-lambda-java-boilerplate: Could not resolve dependencies for project com.cagataygurturk:aws-lambda-java-boilerplate:jar:0.0.1: Failed to collect dependencies at com.cagataygurturk:aws-lambda-local-runner:jar:0.0.1: Failed to read artifact descriptor for com.cagataygurturk:aws-lambda-local-runner:jar:0.0.1: Could not transfer artifact com.cagataygurturk:aws-lambda-local-runner:pom:0.0.1 from/to cagatay-gurturk (http://maven.cagataygurturk.com/releases): Access denied to: http://maven.cagataygurturk.com/releases/com/cagataygurturk/aws-lambda-local-runner/0.0.1/aws-lambda-local-runner-0.0.1.pom , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by cagataygurturk** [comment]
Fixed, sorry for the problem.
